dict_my_sql = {}

dict_my_sql["set"] = {}
dict_my_sql["insert"] = {}

dict_my_sql["set"]["VARCHAR"] = " {col_name} = '{value}',"
dict_my_sql["set"]["BIN"] =  " {col_name} = '{value}',"
dict_my_sql["set"]["VARBIN"] =  " {col_name} = '{value}',"
dict_my_sql["set"]["CHAR"] = " {col_name} = '{value}',"
dict_my_sql["set"]["TINYTEXT"] = " {col_name} = '{value}',"
dict_my_sql["set"]["TEXT"] = " {col_name} = '{value}',"
dict_my_sql["set"]["MEDIUMTEXT"] = " {col_name} = '{value}',"
dict_my_sql["set"]["LONGTEXT"] =  " {col_name} = '{value}',"
dict_my_sql["set"]["BIT"] = " {col_name} = '{value}',"
dict_my_sql["set"]["TINYINT"] =  " {col_name} = {value},"
dict_my_sql["set"]["SMALLINT"] = " {col_name} = {value},"
dict_my_sql["set"]["MEDIUMINT"] = " {col_name} = {value},"
dict_my_sql["set"]["INT"] =  " {col_name} = {value},"
dict_my_sql["set"]["INTEGER"] = " {col_name} = {value},"
dict_my_sql["set"]["BIGINT"] = " {col_name} = {value},"
dict_my_sql["set"]["FLOAT"] = " {col_name} = {value},"
dict_my_sql["set"]["DOUBLE"] = " {col_name} = {value},"
dict_my_sql["set"]["DECIMAL"] = " {col_name} = {value},"
dict_my_sql["set"]["DATE"] = " {col_name} = '{value}',"
dict_my_sql["set"]["DATETIME"] = " {col_name} = '{value}',"
dict_my_sql["set"]["TIMESTAMP"] = " {col_name} = '{value}',"
dict_my_sql["set"]["NULL"] = " {col_name} = {value},"


dict_my_sql["insert"]["VARCHAR"] =  "'{value}'"
dict_my_sql["insert"]["BIN"] =   "'{value}'"
dict_my_sql["insert"]["VARBIN"] =  "'{value}'"
dict_my_sql["insert"]["CHAR"] =  "'{value}'"
dict_my_sql["insert"]["TINYTEXT"] = "'{value}'"
dict_my_sql["insert"]["TEXT"] = "'{value}'"
dict_my_sql["insert"]["MEDIUMTEXT"] = "'{value}'"
dict_my_sql["insert"]["LONGTEXT"] = "'{value}'"
dict_my_sql["insert"]["BIT"] = "'{value}'"
dict_my_sql["insert"]["TINYINT"] = " {value}"
dict_my_sql["insert"]["SMALLINT"] = " {value}"
dict_my_sql["insert"]["MEDIUMINT"] =  " {value}"
dict_my_sql["insert"]["INT"] = " {value}"
dict_my_sql["insert"]["INTEGER"] = " {value}"
dict_my_sql["insert"]["BIGINT"] = " {value}"
dict_my_sql["insert"]["FLOAT"] = " {value}"
dict_my_sql["insert"]["DOUBLE"] = " {value}"
dict_my_sql["insert"]["DECIMAL"] = "{value}"
dict_my_sql["insert"]["DATE"] =  " '{value}'"
dict_my_sql["insert"]["DATETIME"] =  " '{value}'"
dict_my_sql["insert"]["TIMESTAMP"] = " '{value}'"
dict_my_sql["insert"]["NULL"] = " {value}"

#-------------------------------------------------------------------------------------

dict_sql_server = {}

dict_sql_server["set"] = {}
dict_sql_server["insert"] = {}

dict_sql_server["set"]["VARCHAR"] = " {col_name} = '{value}',"
dict_sql_server["set"]["NVARCHAR"] = " {col_name} = '{value}',"
dict_sql_server["set"]["BIN"] = " {col_name} = '{value}',"
dict_sql_server["set"]["VARBIN"] = " {col_name} = '{value}',"
dict_sql_server["set"]["CHAR"] = " {col_name} = '{value}',"
dict_sql_server["set"]["NCHAR"] = " {col_name} = '{value}',"
dict_sql_server["set"]["TEXT"] = " {col_name} = '{value}',"
dict_sql_server["set"]["NTEXT"] = " {col_name} = '{value}',"
dict_sql_server["set"]["TINYINT"] = " {col_name} = {value},"
dict_sql_server["set"]["SMALLINT"] = " {col_name} = {value},"
dict_sql_server["set"]["INT"] = " {col_name} = {value},"
dict_sql_server["set"]["BIGINT"] = " {col_name} = {value},"
dict_sql_server["set"]["FLOAT"] = " {col_name} = {value},"
dict_sql_server["set"]["NUMERIC"] = " {col_name} = {value},"
dict_sql_server["set"]["DATE"] =" {col_name} = '{value}',"
dict_sql_server["set"]["DATETIME"] = " {col_name} = '{value}',"
dict_sql_server["set"]["DATETIME2"] = " {col_name} = '{value}',"
dict_sql_server["set"]["SMALLDATETIME"] = " {col_name} = '{value}',"
dict_sql_server["set"]["TIMESTAMP"] = " {col_name} = '{value}',"
dict_sql_server["set"]["REAL"] = " {col_name} = {value},"
dict_sql_server["set"]["DECIMAL"] =  " {col_name} = {value},"
dict_sql_server["set"]["BINARY"] = " {col_name} = '{value}',"
dict_sql_server["set"]["BIT"] = " {col_name} = {value},"
dict_sql_server["set"]["DATETIMEOFFSET"] = " {col_name} = '{value}',"
dict_sql_server["set"]["TIME"] = " {col_name} = '{value}',"
dict_sql_server["set"]["SMALLMONEY"] = " {col_name} = {value},"
dict_sql_server["set"]["MONEY"] = " {col_name} = {value},"
dict_sql_server["set"]["NULL"] = " {col_name} = {value},"


dict_sql_server["insert"]["VARCHAR"] = "'{value}'"
dict_sql_server["insert"]["NVARCHAR"] = "'{value}'"
dict_sql_server["insert"]["BIN"] = "'{value}'"
dict_sql_server["insert"]["VARBIN"] = "'{value}'"
dict_sql_server["insert"]["CHAR"] = "'{value}'"
dict_sql_server["insert"]["NCHAR"] =  " '{value}'"
dict_sql_server["insert"]["TEXT"] = "'{value}'"
dict_sql_server["insert"]["NTEXT"] = "'{value}',"
dict_sql_server["insert"]["TINYINT"] = " {value}"
dict_sql_server["insert"]["SMALLINT"] = " {value}"
dict_sql_server["insert"]["INT"] =" {value}"
dict_sql_server["insert"]["BIGINT"] = " {value}"
dict_sql_server["insert"]["FLOAT"] =" {value}"
dict_sql_server["insert"]["NUMERIC"] = " {value}"
dict_sql_server["insert"]["DATE"] =  " '{value}'"
dict_sql_server["insert"]["DATETIME"] =  " '{value}'"
dict_sql_server["insert"]["DATETIME2"] =  " '{value}'"
dict_sql_server["insert"]["SMALLDATETIME"] =  " '{value}'"
dict_sql_server["insert"]["TIMESTAMP"] =  " '{value}'"
dict_sql_server["insert"]["REAL"] = " {value}"
dict_sql_server["insert"]["DECIMAL"] = "{value}"
dict_sql_server["insert"]["BINARY"] = "'{value}'"
dict_sql_server["insert"]["BIT"] = "{value}"
dict_sql_server["insert"]["DATETIMEOFFSET"] = " '{value}'"
dict_sql_server["insert"]["TIME"] = " '{value}'"
dict_sql_server["insert"]["SMALLMONEY"] = "{value}"
dict_sql_server["insert"]["MONEY"] = "{value}"
dict_sql_server["insert"]["NULL"] = " {value}"

#-------------------------------------------------------------------------------------


dict_postgres = {}

dict_postgres["set"] = {}
dict_postgres["insert"] = {}


dict_postgres["set"]["BIGINT"] = " {col_name} = {value},"
dict_postgres["set"]["BIGSERIAL"] = " {col_name} = {value},"
dict_postgres["set"]["CHARACTER"] = " {col_name} = '{value}',"
dict_postgres["set"]["CHARACTER VARYING"] = " {col_name} = '{value}',"
dict_postgres["set"]["DATE"] = " {col_name} = '{value}',"
dict_postgres["set"]["DOUBLE PRECISION"] = " {col_name} = {value},"
dict_postgres["set"]["INTEGER"] = " {col_name} = {value},"
dict_postgres["set"]["NUMERIC"] = " {col_name} = {value},"
dict_postgres["set"]["REAL"] = " {col_name} = {value},"
dict_postgres["set"]["SMALLINT"] = " {col_name} = {value},"
dict_postgres["set"]["SMALSERIAL"] = " {col_name} = {value},"
dict_postgres["set"]["SERIAL"] = " {col_name} = {value},"
dict_postgres["set"]["SERIAL2"] = " {col_name} = {value},"
dict_postgres["set"]["SERIAL8"] = " {col_name} = {value},"
dict_postgres["set"]["TEXT"] = " {col_name} = '{value}',"
dict_postgres["set"]["TIMESTAMP"] = " {col_name} = '{value}',"
dict_postgres["set"]["BOOLEAN"] = " {col_name} = '{value}',"
dict_postgres["set"]["BYTEA"] = " {col_name} = '{value}',"
dict_postgres["set"]["FLOAT4"] = " {col_name} = {value},"
dict_postgres["set"]["INT4"] = " {col_name} = {value},"
dict_postgres["set"]["TIMESTAMP WITHOUT TIME ZONE"] = " {col_name} = '{value}',"
dict_postgres["set"]["NULL"] = " {col_name} = {value},"

dict_postgres["insert"]["BIGINT"] = "{value}"
dict_postgres["insert"]["BIGSERIAL"] = "{value}"
dict_postgres["insert"]["CHARACTER"] = " '{value}'"
dict_postgres["insert"]["CHARACTER VARYING"] = " '{value}'"
dict_postgres["insert"]["DATE"] = " '{value}'"
dict_postgres["insert"]["DOUBLE PRECISION"] = "{value}"
dict_postgres["insert"]["INTEGER"] = "{value}"
dict_postgres["insert"]["NUMERIC"] = "{value}"
dict_postgres["insert"]["REAL"] = "{value}"
dict_postgres["insert"]["SMALLINT"] = "{value}"
dict_postgres["insert"]["SMALSERIAL"] = "{value}"
dict_postgres["insert"]["SERIAL"] = "{value}"
dict_postgres["insert"]["SERIAL2"] = "{value}"
dict_postgres["insert"]["SERIAL8"] = "{value}"
dict_postgres["insert"]["TEXT"] = " '{value}'"
dict_postgres["insert"]["TIMESTAMP"] = " '{value}'"
dict_postgres["insert"]["BOOLEAN"] =  " '{value}'"
dict_postgres["insert"]["BYTEA"] = " '{value}'"
dict_postgres["insert"]["FLOAT4"] = "{value}"
dict_postgres["insert"]["INT4"] = "{value}"
dict_postgres["insert"]["TIMESTAMP WITHOUT TIME ZONE"] = " '{value}'"
dict_postgres["insert"]["NULL"] = " {value}"


#-------------------------------------------------------------------------------------


dict_oracle = {}

dict_oracle["set"] = {}
dict_oracle["insert"] = {}


dict_oracle["set"]["VARCHAR"] = " {col_name} = '{value}',"
dict_oracle["set"]["VARCHAR2"] = " {col_name} = '{value}',"
dict_oracle["set"]["CHAR"] = " {col_name} = '{value}',"
dict_oracle["set"]["BIN_DOUBLE"] = " {col_name} = {value},"
dict_oracle["set"]["BIN_FLOAT"] = " {col_name} = {value},"
dict_oracle["set"]["DATE"] = " {col_name} = TO_DATE(SUBSTR('{value}', 1, 10), 'YYYY-MM-DD'),"
dict_oracle["set"]["DECIMAL"] = " {col_name} = {value},"
dict_oracle["set"]["DOUBLE PRECISION"] = " {col_name} = {value},"
dict_oracle["set"]["FLOAT"] = " {col_name} = {value},"
dict_oracle["set"]["INTEGER"] = " {col_name} = {value},"
dict_oracle["set"]["LONG"] = " {col_name} = '{value}',"
dict_oracle["set"]["LONG RAW"] = " {col_name} = '{value}',"
dict_oracle["set"]["NCHAR"] = " {col_name} = '{value}',"
dict_oracle["set"]["NUMBER"] = " {col_name} = {value},"
dict_oracle["set"]["NVARCHAR2"] = " {col_name} = '{value}',"
dict_oracle["set"]["RAW"] = " {col_name} = '{value}',"
dict_oracle["set"]["REAL"] = " {col_name} = {value},"
dict_oracle["set"]["SIGNED BIN INTEGER"] = " {col_name} = {value},"
dict_oracle["set"]["SMALLINT"] = " {col_name} = {value},"
dict_oracle["set"]["TIME WITH TZ"] = " {col_name} = TO_TIMESTAMP('{value}', 'YYYY-MM-DD HH24:MI:SS'),"
dict_oracle["set"]["TIMESTAMP"] = " {col_name} = TO_TIMESTAMP('{value}', 'YYYY-MM-DD HH24:MI:SS'),"
dict_oracle["set"]["TIMESTAMP WITH LOCAL TIME ZONE"] = " {col_name} = TO_TIMESTAMP('{value}', 'YYYY-MM-DD HH24:MI:SS'),"
dict_oracle["set"]["TIMESTAMP WITH LOCAL TZ"] = " {col_name} = TO_TIMESTAMP('{value}', 'YYYY-MM-DD HH24:MI:SS'),"
dict_oracle["set"]["TIMESTAMP WITH TIME ZONE"] = " {col_name} = TO_TIMESTAMP('{value}', 'YYYY-MM-DD HH24:MI:SS'),"
dict_oracle["set"]["TIMESTAMP WITHOUT TIME ZONE"] = " {col_name} = TO_TIMESTAMP('{value}', 'YYYY-MM-DD HH24:MI:SS'),"
dict_oracle["set"]["TIMESTAMP WITH TZ"] = " {col_name} = TO_TIMESTAMP('{value}', 'YYYY-MM-DD HH24:MI:SS'),"
dict_oracle["set"]["UNSIGNED BIN INTEGER"] = " {col_name} = {value},"
dict_oracle["set"]["CLOB"] = " {col_name} = '{value}',"
dict_oracle["set"]["BLOB"] = " {col_name} = '{value}',"
dict_oracle["set"]["BFILE"] = " {col_name} = '{value}',"
dict_oracle["set"]["BINARY ROWID"] = " {col_name} = {value},"
dict_oracle["set"]["CFILE"] = " {col_name} = '{value}',"
dict_oracle["set"]["INTERVAL DAY TO SECOND"] = " {col_name} = TO_TIMESTAMP('{value}', 'YYYY-MM-DD HH24:MI:SS'),"
dict_oracle["set"]["INTERVAL YEAR TO MONTH"] = " {col_name} = TO_TIMESTAMP('{value}', 'YYYY-MM-DD HH24:MI:SS'),"
dict_oracle["set"]["NCLOB"] = " {col_name} = '{value}',"
dict_oracle["set"]["OCTET"] = " {col_name} = {value},"
dict_oracle["set"]["ROWID"] = " {col_name} = {value},"
dict_oracle["set"]["TIME"] = " {col_name} = TO_TIMESTAMP('{value}', 'YYYY-MM-DD HH24:MI:SS'),"
dict_oracle["set"]["UROWID"] = " {col_name} = {value},"
dict_oracle["set"]["VARRAY"] = " {col_name} = {value},"
dict_oracle["set"]["VARYING ARRAY"] = " {col_name} = {value},"
dict_oracle["set"]["NULL"] = " {col_name} = {value},"

dict_oracle["insert"]["VARCHAR"] = "'{value}'"
dict_oracle["insert"]["VARCHAR2"] = "'{value}'"
dict_oracle["insert"]["CHAR"] = "'{value}'"
dict_oracle["insert"]["BIN_DOUBLE"] = "{value}"
dict_oracle["insert"]["BIN_FLOAT"] = "{value}"
dict_oracle["insert"]["DATE"] = "TO_DATE(SUBSTR('{value}',1,10), 'YYYY-MM-DD')"
dict_oracle["insert"]["DECIMAL"] = "{value}"
dict_oracle["insert"]["DOUBLE PRECISION"] = " {value}"
dict_oracle["insert"]["FLOAT"] = " {value}"
dict_oracle["insert"]["INTEGER"] = " {value}"
dict_oracle["insert"]["LONG"] = " '{value}'"
dict_oracle["insert"]["LONG RAW"] = " '{value}'"
dict_oracle["insert"]["NCHAR"] = " '{value}'"
dict_oracle["insert"]["NUMBER"] = " {value}"
dict_oracle["insert"]["NVARCHAR2"] = " '{value}'"
dict_oracle["insert"]["RAW"] = " '{value}'"
dict_oracle["insert"]["REAL"] = " {value}"
dict_oracle["insert"]["SIGNED BIN INTEGER"] = " {value}"
dict_oracle["insert"]["SMALLINT"] = " {value}"
dict_oracle["insert"]["TIME WITH TZ"] = " TO_TIMESTAMP('{value}', 'YYYY-MM-DD HH24:MI:SS')"
dict_oracle["insert"]["TIMESTAMP"] = " TO_TIMESTAMP('{value}', 'YYYY-MM-DD HH24:MI:SS')"
dict_oracle["insert"]["TIMESTAMP WITH LOCAL TIME ZONE"] = " TO_TIMESTAMP('{value}', 'YYYY-MM-DD HH24:MI:SS')"
dict_oracle["insert"]["TIMESTAMP WITH LOCAL TZ"] = " TO_TIMESTAMP('{value}', 'YYYY-MM-DD HH24:MI:SS')"
dict_oracle["insert"]["TIMESTAMP WITH TIME ZONE"] = " TO_TIMESTAMP('{value}', 'YYYY-MM-DD HH24:MI:SS')"
dict_oracle["insert"]["TIMESTAMP WITHOUT TIME ZONE"] = " TO_TIMESTAMP('{value}', 'YYYY-MM-DD HH24:MI:SS')"
dict_oracle["insert"]["TIMESTAMP WITH TZ"] = " TO_TIMESTAMP('{value}', 'YYYY-MM-DD HH24:MI:SS')"
dict_oracle["insert"]["UNSIGNED BIN INTEGER"] = " {value}"
dict_oracle["insert"]["CLOB"] = " '{value}'"
dict_oracle["insert"]["BLOB"] = " '{value}'"
dict_oracle["insert"]["BFILE"] = " '{value}'"
dict_oracle["insert"]["BINARY ROWID"] = " {value}"
dict_oracle["insert"]["CFILE"] = " '{value}'"
dict_oracle["insert"]["INTERVAL DAY TO SECOND"] = " TO_TIMESTAMP('{value}', 'YYYY-MM-DD HH24:MI:SS')"
dict_oracle["insert"]["INTERVAL YEAR TO MONTH"] = " TO_TIMESTAMP('{value}', 'YYYY-MM-DD HH24:MI:SS')"
dict_oracle["insert"]["NCLOB"] = " '{value}'"
dict_oracle["insert"]["OCTET"] = " {value}"
dict_oracle["insert"]["ROWID"] = " {value}"
dict_oracle["insert"]["TIME"] = " TO_TIMESTAMP('{value}', 'YYYY-MM-DD HH24:MI:SS')"
dict_oracle["insert"]["UROWID"] = " {value}"
dict_oracle["insert"]["VARRAY"] = " {value}"
dict_oracle["insert"]["VARYING ARRAY"] = " {value}"
dict_oracle["insert"]["NULL"] = " {value}"

#-------------------------------------------------------------------------------------
dict_db2 = {}
dict_db2["set"] = {}
dict_db2["insert"] = {}

dict_db2["set"]["BIGINT"] = " {col_name} = {value},"
dict_db2["set"]["BIN LARGE OBJECT"] = " {col_name} = '{value}',"
dict_db2["set"]["CHARACTER"] = " {col_name} = '{value}',"
dict_db2["set"]["CHAR"] = " {col_name} = '{value}',"
dict_db2["set"]["CHARACTER LARGE OBJECT"] = " {col_name} = {value},"
dict_db2["set"]["CHARACTER VARYING"] = " {col_name} = '{value}',"
dict_db2["set"]["DECIMAL"] = " {col_name} = {value},"
dict_db2["set"]["DOUBLE PRECISION"] = " {col_name} = {value},"
dict_db2["set"]["VARCHAR"] = " {col_name} = '{value}',"
dict_db2["set"]["LONG VARCHAR"] = " {col_name} = '{value}',"
dict_db2["set"]["SMALLINT"] = " {col_name} = {value},"
dict_db2["set"]["INTEGER"] = " {col_name} = {value},"
dict_db2["set"]["DECFLOAT"] = " {col_name} = {value},"
dict_db2["set"]["DOUBLE"] = " {col_name} = {value},"
dict_db2["set"]["REAL"] = " {col_name} = {value},"
dict_db2["set"]["FLOAT"] = " {col_name} = {value},"
dict_db2["set"]["NUMERIC"] = " {col_name} = {value},"
dict_db2["set"]["TIMESTAMP"] = " {col_name} = '{value}',"
dict_db2["set"]["DATE"] = " {col_name} = '{value}',"
dict_db2["set"]["BIN"] = " {col_name} = '{value}',"
dict_db2["set"]["VARBIN"] = " {col_name} = '{value}',"
dict_db2["set"]["NULL"] = " {col_name} = {value},"


dict_db2["insert"]["BIGINT"] = "{value}"
dict_db2["insert"]["BIN LARGE OBJECT"] = " '{value}'"
dict_db2["insert"]["CHARACTER"] = " '{value}'"
dict_db2["insert"]["CHAR"] = " '{value}'"
dict_db2["insert"]["CHARACTER LARGE OBJECT"] = "{value}"
dict_db2["insert"]["CHARACTER VARYING"] = " '{value}'"
dict_db2["insert"]["DECIMAL"] =  "{value}"
dict_db2["insert"]["DOUBLE PRECISION"] =  "{value}"
dict_db2["insert"]["VARCHAR"] = " '{value}'"
dict_db2["insert"]["LONG VARCHAR"] = " '{value}'"
dict_db2["insert"]["SMALLINT"] =  "{value}"
dict_db2["insert"]["INTEGER"] =  "{value}"
dict_db2["insert"]["DECFLOAT"] =  "{value}"
dict_db2["insert"]["DOUBLE"] =  "{value}"
dict_db2["insert"]["REAL"] =  "{value}"
dict_db2["insert"]["FLOAT"] =  "{value}"
dict_db2["insert"]["NUMERIC"] =  "{value}"
dict_db2["insert"]["TIMESTAMP"] = " '{value}'"
dict_db2["insert"]["DATE"] = " '{value}'"
dict_db2["insert"]["BIN"] =  " '{value}'"
dict_db2["insert"]["VARBIN"] = " '{value}'"
dict_db2["insert"]["NULL"] = " {value}"

#-------------------------------------------------------------------------------------

dict_tera_data = {}

dict_tera_data["set"] = {}
dict_tera_data["insert"] = {}

dict_tera_data["set"]["A1"] = " {col_name} = '{value}',"
dict_tera_data["set"]["AN"] = " {col_name} = '{value}',"
dict_tera_data["set"]["I8"] = " {col_name} = {value},"
dict_tera_data["set"]["BO"] = " {col_name} = '{value}',"
dict_tera_data["set"]["BF"] =  " {col_name} = {value},"
dict_tera_data["set"]["BV"] =  " {col_name} = {value},"
dict_tera_data["set"]["I1"] = " {col_name} = {value},"
dict_tera_data["set"]["CF"] = " {col_name} = '{value}',"
dict_tera_data["set"]["CV"] = " {col_name} = '{value}',"
dict_tera_data["set"]["CO"] = " {col_name} = '{value}',"
dict_tera_data["set"]["D"] = " {col_name} = {value},"
dict_tera_data["set"]["DA"] = " {col_name} = '{value}',"
dict_tera_data["set"]["F"] = " {col_name} = {value},"
dict_tera_data["set"]["I"] = " {col_name} = {value},"
dict_tera_data["set"]["DY"] = " {col_name} = {value},"
dict_tera_data["set"]["DH"] = " {col_name} = {value},"
dict_tera_data["set"]["DM"] = " {col_name} = {value},"
dict_tera_data["set"]["HR"] = " {col_name} = {value},"
dict_tera_data["set"]["HM"] = " {col_name} = {value},"
dict_tera_data["set"]["HS"] = " {col_name} = {value},"
dict_tera_data["set"]["MI"] = " {col_name} = {value},"
dict_tera_data["set"]["MS"] = " {col_name} = {value},"
dict_tera_data["set"]["MO"] = " {col_name} = {value},"
dict_tera_data["set"]["SC"] = " {col_name} = {value},"
dict_tera_data["set"]["YR"] = " {col_name} = {value},"
dict_tera_data["set"]["YM"] = " {col_name} = {value},"
dict_tera_data["set"]["N"] = " {col_name} = {value},"
dict_tera_data["set"]["PD"] = " {col_name} = {value},"
dict_tera_data["set"]["PT"] = " {col_name} = {value},"
dict_tera_data["set"]["PZ"] = " {col_name} = {value},"
dict_tera_data["set"]["PS"] = " {col_name} = {value},"
dict_tera_data["set"]["PM"] = " {col_name} = {value},"
dict_tera_data["set"]["I2"] = " {col_name} = {value},"
dict_tera_data["set"]["AT"] = " {col_name} = {value},"
dict_tera_data["set"]["TS"] = " {col_name} = '{value}',"
dict_tera_data["set"]["TZ"] = " {col_name} = '{value}',"
dict_tera_data["set"]["SZ"] = " {col_name} = '{value}',"
dict_tera_data["set"]["INTEGER"] = " {col_name} = {value},"
dict_tera_data["set"]["CHAR"] = " {col_name} = '{value}',"
dict_tera_data["set"]["TIMESTAMP"] = " {col_name} = '{value}',"
dict_tera_data["set"]["BYTE"] = " {col_name} = '{value}',"   
dict_tera_data["set"]["SMALLINT"] = " {col_name} = {value},"
dict_tera_data["set"]["BYTEINT"] = " {col_name} = {value},"   
dict_tera_data["set"]["VARCHAR"] = " {col_name} = '{value}',"
dict_tera_data["set"]["DATE"] = " {col_name} = '{value}',"
dict_tera_data["set"]["FLOAT"] = " {col_name} = {value},"
dict_tera_data["set"]["NULL"] = " {col_name} = {value},"



dict_tera_data["insert"]["A1"] = " '{value}'"
dict_tera_data["insert"]["AN"] = " '{value}'"
dict_tera_data["insert"]["I8"] =  "{value}"
dict_tera_data["insert"]["BO"] =  " '{value}'"
dict_tera_data["insert"]["BF"] =  "{value}"
dict_tera_data["insert"]["BV"] =  "{value}"
dict_tera_data["insert"]["I1"] =  "{value}"
dict_tera_data["insert"]["CF"] = " '{value}'"
dict_tera_data["insert"]["CV"] = " '{value}'"
dict_tera_data["insert"]["CO"] = " '{value}'"
dict_tera_data["insert"]["D"] =  "{value}"
dict_tera_data["insert"]["DA"] = " '{value}'"
dict_tera_data["insert"]["F"] =  "{value}"
dict_tera_data["insert"]["I"] =  "{value}"
dict_tera_data["insert"]["DY"] =  "{value}"
dict_tera_data["insert"]["DH"] =  "{value}"
dict_tera_data["insert"]["DM"] =  "{value}"
dict_tera_data["insert"]["HR"] =  "{value}"
dict_tera_data["insert"]["HM"] =  "{value}"
dict_tera_data["insert"]["HS"] =  "{value}"
dict_tera_data["insert"]["MI"] =  "{value}"
dict_tera_data["insert"]["MS"] =  "{value}"
dict_tera_data["insert"]["MO"] =  "{value}"
dict_tera_data["insert"]["SC"] =  "{value}"
dict_tera_data["insert"]["YR"] =  "{value}"
dict_tera_data["insert"]["YM"] =  "{value}"
dict_tera_data["insert"]["N"] =  "{value}"
dict_tera_data["insert"]["PD"] =  "{value}"
dict_tera_data["insert"]["PT"] =  "{value}"
dict_tera_data["insert"]["PZ"] =  "{value}"
dict_tera_data["insert"]["PS"] =  "{value}"
dict_tera_data["insert"]["PM"] =  "{value}"
dict_tera_data["insert"]["I2"] =  "{value}"
dict_tera_data["insert"]["AT"] =  "{value}"
dict_tera_data["insert"]["TS"] =  " '{value}'"
dict_tera_data["insert"]["TZ"] =  " '{value}'"
dict_tera_data["insert"]["SZ"] =  " '{value}'"
dict_tera_data["insert"]["INTEGER"] =  "{value}"
dict_tera_data["insert"]["CHAR"] = " '{value}'"
dict_tera_data["insert"]["TIMESTAMP"] =  " '{value}'"
dict_tera_data["insert"]["BYTE"] = " '{value}'"
dict_tera_data["insert"]["SMALLINT"] =  "{value}"
dict_tera_data["insert"]["BYTEINT"] =  "{value}"
dict_tera_data["insert"]["VARCHAR"] = " '{value}'"
dict_tera_data["insert"]["DATE"] = " '{value}'"
dict_tera_data["insert"]["FLOAT"] =  "{value}"
dict_tera_data["insert"]["NULL"] = " {value}"

#-------------------------------------------------------------------------------------

dict_sap_hana = {}

dict_sap_hana["set"] = {}
dict_sap_hana["insert"] = {}

dict_sap_hana["set"]["VARCHAR"] = " {col_name} = '{value}',"
dict_sap_hana["set"]["BINARY"] = " {col_name} = '{value}',"
dict_sap_hana["set"]["VARBINARY"] = " {col_name} = '{value}',"
dict_sap_hana["set"]["CHAR"] = " {col_name} = '{value}',"
dict_sap_hana["set"]["TINYTEXT"] = " {col_name} = '{value}',"
dict_sap_hana["set"]["TEXT"] = " {col_name} = '{value}',"
dict_sap_hana["set"]["MEDIUMTEXT"] = " {col_name} = '{value}',"
dict_sap_hana["set"]["LONGTEXT"] = " {col_name} = '{value}',"
dict_sap_hana["set"]["BIT"] =  " {col_name} = '{value}',"
dict_sap_hana["set"]["TINYINT"] = " {col_name} = {value},"
dict_sap_hana["set"]["SMALLINT"] = " {col_name} = {value},"
dict_sap_hana["set"]["MEDIUMINT"] = " {col_name} = {value},"
dict_sap_hana["set"]["INT"] = " {col_name} = {value},"
dict_sap_hana["set"]["INTEGER"] = " {col_name} = {value},"
dict_sap_hana["set"]["BIGINT"] = " {col_name} = {value},"
dict_sap_hana["set"]["FLOAT"] = " {col_name} = {value},"
dict_sap_hana["set"]["DOUBLE"] = " {col_name} = {value},"
dict_sap_hana["set"]["DECIMAL"] = " {col_name} = {value},"
dict_sap_hana["set"]["DATE"] = " {col_name} = '{value}',"
dict_sap_hana["set"]["DATETIME"] = " {col_name} = '{value}',"
dict_sap_hana["set"]["TIMESTAMP"] = " {col_name} = '{value}',"
dict_sap_hana["set"]["REAL"] = " {col_name} = {value},"
dict_sap_hana["set"]["NULL"] = " {col_name} = {value},"



dict_sap_hana["insert"]["VARCHAR"] = " '{value}'"
dict_sap_hana["insert"]["BINARY"] = " '{value}'"
dict_sap_hana["insert"]["VARBINARY"] = " '{value}'"
dict_sap_hana["insert"]["CHAR"] = " '{value}'"
dict_sap_hana["insert"]["TINYTEXT"] = " '{value}'"
dict_sap_hana["insert"]["TEXT"] = " '{value}'"
dict_sap_hana["insert"]["MEDIUMTEXT"] = " '{value}'"
dict_sap_hana["insert"]["LONGTEXT"] = " '{value}'"
dict_sap_hana["insert"]["BIT"] = " '{value}'"
dict_sap_hana["insert"]["TINYINT"] = "{value}"
dict_sap_hana["insert"]["SMALLINT"] = "{value}"
dict_sap_hana["insert"]["MEDIUMINT"] = "{value}"
dict_sap_hana["insert"]["INT"] = "{value}"
dict_sap_hana["insert"]["INTEGER"] = "{value}"
dict_sap_hana["insert"]["BIGINT"] = "{value}"
dict_sap_hana["insert"]["FLOAT"] = "{value}"
dict_sap_hana["insert"]["DOUBLE"] = "{value}"
dict_sap_hana["insert"]["DECIMAL"] = "{value}"
dict_sap_hana["insert"]["DATE"] = " '{value}'"
dict_sap_hana["insert"]["DATETIME"] =  " '{value}'"
dict_sap_hana["insert"]["TIMESTAMP"] = " '{value}'"
dict_sap_hana["insert"]["REAL"] = "{value}"
dict_sap_hana["insert"]["NULL"] = " {value}"

#-------------------------------------------------------------------------------------

dict_snowflake = {}

dict_snowflake["set"] = {}
dict_snowflake["insert"] = {}

dict_snowflake["set"]["VARCHAR"] = " {col_name} = '{value}',"
dict_snowflake["set"]["BINARY"] = " {col_name} = '{value}',"
dict_snowflake["set"]["VARBINARY"] = " {col_name} = '{value}',"
dict_snowflake["set"]["CHAR"] = " {col_name} = '{value}',"
dict_snowflake["set"]["TINYTEXT"] = " {col_name} = '{value}',"
dict_snowflake["set"]["TEXT"] = " {col_name} = '{value}',"
dict_snowflake["set"]["MEDIUMTEXT "] = " {col_name} = '{value}',"
dict_snowflake["set"]["LONGTEXT"] = " {col_name} = '{value}',"
dict_snowflake["set"]["STRING"] = " {col_name} = '{value}',"
dict_snowflake["set"]["BIT"] = " {col_name} = '{value}',"
dict_snowflake["set"]["TINYINT"] = " {col_name} = {value},"
dict_snowflake["set"]["SMALLINT"] = " {col_name} = {value},"
dict_snowflake["set"]["MEDIUMINT"] = " {col_name} = {value},"
dict_snowflake["set"]["BIGINT"] = " {col_name} = {value},"
dict_snowflake["set"]["BYTEINT"] = " {col_name} = {value},"
dict_snowflake["set"]["INT"] = " {col_name} = {value},"
dict_snowflake["set"]["INTEGER"] = " {col_name} = {value},"
dict_snowflake["set"]["NUMBER"] = " {col_name} = {value},"
dict_snowflake["set"]["NUMERIC"] = " {col_name} = {value},"
dict_snowflake["set"]["FLOAT4"] = " {col_name} = {value},"
dict_snowflake["set"]["FLOAT8"] = " {col_name} = {value},"
dict_snowflake["set"]["FLOAT"] = " {col_name} = {value},"
dict_snowflake["set"]["DOUBLE"] = " {col_name} = {value},"
dict_snowflake["set"]["DOUBLE PRECISION"] = " {col_name} = {value},"
dict_snowflake["set"]["DECIMAL"] = " {col_name} = {value},"
dict_snowflake["set"]["DATE"] = " {col_name} = '{value}',"
dict_snowflake["set"]["DATETIME"] = " {col_name} = '{value}',"
dict_snowflake["set"]["TIMESTAMP"] = " {col_name} = '{value}',"
dict_snowflake["set"]["TIMESTAMP_NTZ"] = " {col_name} = '{value}',"
dict_snowflake["set"]["REAL"] = " {col_name} = {value},"
dict_snowflake["set"]["NULL"] = " {col_name} = {value},"



dict_snowflake["insert"]["VARCHAR"] = " '{value}'"
dict_snowflake["insert"]["BINARY"] = " '{value}'"
dict_snowflake["insert"]["VARBINARY"] = " '{value}'"
dict_snowflake["insert"]["CHAR"] = " '{value}'"
dict_snowflake["insert"]["TINYTEXT"] = " '{value}'"
dict_snowflake["insert"]["TEXT"] = " '{value}'"
dict_snowflake["insert"]["MEDIUMTEXT "] = " '{value}'"
dict_snowflake["insert"]["LONGTEXT"] = " '{value}'"
dict_snowflake["insert"]["STRING"] = " '{value}'"
dict_snowflake["insert"]["BIT"] = " '{value}'"
dict_snowflake["insert"]["TINYINT"] = "{value}"
dict_snowflake["insert"]["SMALLINT"] = "{value}"
dict_snowflake["insert"]["MEDIUMINT"] = "{value}"
dict_snowflake["insert"]["BIGINT"] = "{value}"
dict_snowflake["insert"]["BYTEINT"] = "{value}"
dict_snowflake["insert"]["INT"] = "{value}"
dict_snowflake["insert"]["INTEGER"] = "{value}"
dict_snowflake["insert"]["NUMBER"] = "{value}"
dict_snowflake["insert"]["NUMERIC"] = "{value}"
dict_snowflake["insert"]["FLOAT4"] = "{value}"
dict_snowflake["insert"]["FLOAT8"] = "{value}"
dict_snowflake["insert"]["FLOAT"] = "{value}"
dict_snowflake["insert"]["DOUBLE"] = "{value}"
dict_snowflake["insert"]["DOUBLE PRECISION"] = "{value}"
dict_snowflake["insert"]["DECIMAL"] = "{value}"
dict_snowflake["insert"]["DATE"] = " '{value}'"
dict_snowflake["insert"]["DATETIME"] = " '{value}'"
dict_snowflake["insert"]["TIMESTAMP"] = " '{value}'"
dict_snowflake["insert"]["TIMESTAMP_NTZ"] = " '{value}'"
dict_snowflake["insert"]["REAL"] = "{value}"
dict_snowflake["insert"]["NULL"] = " {value}"

#-------------------------------------------------------------------------------------

dict_rfc = {}

dict_rfc["set"] = {}
dict_rfc["insert"] = {}


dict_rfc["set"]["CLNT"] = " {col_name} = '{value}',"
dict_rfc["set"]["CHAR"] = " {col_name} = '{value}',"
dict_rfc["set"]["CURR"] = " {col_name} = '{value}',"
dict_rfc["set"]["LCHR"] = " {col_name} = '{value}',"
dict_rfc["set"]["SSTRING"] = " {col_name} = '{value}',"
dict_rfc["set"]["STRING"] = " {col_name} = '{value}',"
dict_rfc["set"]["LANG"] = " {col_name} = '{value}',"
dict_rfc["set"]["CUKY"] = " {col_name} = '{value}',"
dict_rfc["set"]["DATS"] =  " {col_name} = '{value}',"
dict_rfc["set"]["TIMS"] =" {col_name} = {value},"
dict_rfc["set"]["DEC"] = " {col_name} = {value},"
dict_rfc["set"]["DF16_DEC"] = " {col_name} = {value},"
dict_rfc["set"]["DF16_RAW"] = " {col_name} = {value},"
dict_rfc["set"]["DF34_DEC"] = " {col_name} = {value},"
dict_rfc["set"]["DF34_RAW"] = " {col_name} = {value},"
dict_rfc["set"]["NUMC"] = " {col_name} = {value},"
dict_rfc["set"]["D34R"] = " {col_name} = '{value}',"
dict_rfc["set"]["ACCP"] = " {col_name} = '{value}',"
dict_rfc["set"]["QUAN"] = " {col_name} = {value},"
dict_rfc["set"]["UNIT"] = " {col_name} = '{value}',"
dict_rfc["set"]["RAW"] = " {col_name} = '{value}',"
dict_rfc["set"]["LRAW"] = " {col_name} = '{value}',"
dict_rfc["set"]["DF16_SCL"] = " {col_name} = '{value}',"
dict_rfc["set"]["DF34_SCL"] = " {col_name} = '{value}',"
dict_rfc["set"]["PREC"] = " {col_name} = '{value}',"
dict_rfc["set"]["VARC"] = " {col_name} = '{value}',"
dict_rfc["set"]["RAWSTRING"] = " {col_name} = '{value}',"
dict_rfc["set"]["FLTP"] = " {col_name} = {value},"
dict_rfc["set"]["INT1"] =" {col_name} = {value},"
dict_rfc["set"]["INT2"] =" {col_name} = {value},"
dict_rfc["set"]["INT4"] =" {col_name} = {value},"
dict_rfc["set"]["INT8"] =" {col_name} = {value},"
dict_rfc["set"]["INT9"] =" {col_name} = {value},"
## BW IO data types
dict_rfc["set"]["I"] =" {col_name} = {value},"
dict_rfc["set"]["N"] =" {col_name} = {value},"
dict_rfc["set"]["P"] = " {col_name} = '{value}',"
dict_rfc["set"]["C"] = " {col_name} = '{value}',"
dict_rfc["set"]["D"] = " {col_name} = '{value}',"
dict_rfc["set"]["NULL"] = " {col_name} = {value},"



dict_rfc["insert"]["CLNT"] = " '{value}'"
dict_rfc["insert"]["CHAR"] = " '{value}'"
dict_rfc["insert"]["CURR"] = " '{value}'"
dict_rfc["insert"]["LCHR"] = " '{value}'"
dict_rfc["insert"]["SSTRING"] = " '{value}'"
dict_rfc["insert"]["STRING"] = " '{value}'"
dict_rfc["insert"]["LANG"] = " '{value}'"
dict_rfc["insert"]["CUKY"] = " '{value}'"
dict_rfc["insert"]["DATS"] = " '{value}'"
dict_rfc["insert"]["TIMS"] = "{value}"
dict_rfc["insert"]["DEC"] = "{value}"
dict_rfc["insert"]["DF16_DEC"] = "{value}"
dict_rfc["insert"]["DF16_RAW"] = "{value}"
dict_rfc["insert"]["DF34_DEC"] = "{value}"
dict_rfc["insert"]["DF34_RAW"] = "{value}"
dict_rfc["insert"]["NUMC"] = "{value}"
dict_rfc["insert"]["D34R"] = " '{value}'"
dict_rfc["insert"]["ACCP"] = " '{value}'"
dict_rfc["insert"]["QUAN"] = "{value}"
dict_rfc["insert"]["UNIT"] = " '{value}'"
dict_rfc["insert"]["RAW"] = " '{value}'"
dict_rfc["insert"]["LRAW"] = " '{value}'"
dict_rfc["insert"]["DF16_SCL"] = " '{value}'"
dict_rfc["insert"]["DF34_SCL"] = " '{value}'"
dict_rfc["insert"]["PREC"] = " '{value}'"
dict_rfc["insert"]["VARC"] = " '{value}'"
dict_rfc["insert"]["RAWSTRING"] = " '{value}'"
dict_rfc["insert"]["FLTP"] = "{value}"
dict_rfc["insert"]["INT1"] = "{value}"
dict_rfc["insert"]["INT2"] = "{value}"
dict_rfc["insert"]["INT4"] = "{value}"
dict_rfc["insert"]["INT8"] = "{value}"
dict_rfc["insert"]["INT9"] = "{value}"
## BW IO data types
dict_rfc["insert"]["I"] = "{value}"
dict_rfc["insert"]["N"] = "{value}"
dict_rfc["insert"]["P"] = " '{value}'"
dict_rfc["insert"]["C"] = " '{value}'"
dict_rfc["insert"]["D"] = " '{value}'"
dict_rfc["insert"]["NULL"] = " {value}"
#-------------------------------------------------------------------------------------

dict_big_query = {}

dict_big_query["set"] = {}
dict_big_query["insert"] = {}

dict_big_query["set"]["BOOL"] = " {col_name} = '{value}',"
dict_big_query["set"]["ARRAY"] = " {col_name} = {value},"
dict_big_query["set"]["STRING"] = " {col_name} = '{value}',"
dict_big_query["set"]["JSON"] = " {col_name} = '{value}',"
dict_big_query["set"]["BYTES"] = " {col_name} = '{value}'," 
dict_big_query["set"]["INT64"] = " {col_name} = {value},"
dict_big_query["set"]["INTERVAL"] = " {col_name} = {value},"
dict_big_query["set"]["FLOAT64"] = " {col_name} = {value},"
dict_big_query["set"]["BIGNUMERIC"] = " {col_name} = {value},"
dict_big_query["set"]["DATE"] = " {col_name} = '{value}'," 
dict_big_query["set"]["DATETIME"] = " {col_name} = '{value}'," 
dict_big_query["set"]["STRUCT"] = " {col_name} = '{value}',"
dict_big_query["set"]["GEOMETRY"] = " {col_name} = '{value}',"
dict_big_query["set"]["RAW"] = " {col_name} = '{value}',"
dict_big_query["set"]["TIMESTAMP"] = " {col_name} = '{value}'," 
dict_big_query["set"]["TIME"] = " {col_name} = '{value}'," 
dict_big_query["set"]["NULL"] = " {col_name} = {value},"


dict_big_query["insert"]["BOOL"] = " '{value}'"
dict_big_query["insert"]["ARRAY"] =  "{value}"
dict_big_query["insert"]["STRING"] = " '{value}'"
dict_big_query["insert"]["JSON"] = " '{value}'"
dict_big_query["insert"]["BYTES"] = " '{value}'"
dict_big_query["insert"]["INT64"] =  "{value}"
dict_big_query["insert"]["INTERVAL"] =  "{value}"
dict_big_query["insert"]["FLOAT64"] =  "{value}"
dict_big_query["insert"]["BIGNUMERIC"] =  "{value}"
dict_big_query["insert"]["DATE"] = " '{value}'"
dict_big_query["insert"]["DATETIME"] = " '{value}'"
dict_big_query["insert"]["STRUCT"] = " '{value}'"
dict_big_query["insert"]["GEOMETRY"] = " '{value}'"
dict_big_query["insert"]["RAW"] = " '{value}'"
dict_big_query["insert"]["TIMESTAMP"] = " '{value}'"
dict_big_query["insert"]["TIME"] = " '{value}'"
dict_big_query["insert"]["NULL"] = " {value}"

#-------------------------------------------------------------------------------------

dict_file_storage = {}

dict_file_storage["set"] = {}
dict_file_storage["insert"] = {}

dict_file_storage["set"]["BOOL"] = " {col_name} = '{value}',"
dict_file_storage["set"]["OBJECT"] = " {col_name} = '{value}',"
dict_file_storage["set"]["INT64"] = " {col_name} = {value},"
dict_file_storage["set"]["INT32"] = " {col_name} = {value},"
dict_file_storage["set"]["INT16"] = " {col_name} = {value},"
dict_file_storage["set"]["INT8"] = " {col_name} = {value},"
dict_file_storage["set"]["CATEGORY"] = " {col_name} = '{value}',"
dict_file_storage["set"]["FLOAT64"] = " {col_name} = {value},"
dict_file_storage["set"]["FLOAT32"] = " {col_name} = {value},"
dict_file_storage["set"]["FLOAT16"] = " {col_name} = {value},"
dict_file_storage["set"]["FLOAT8"] = " {col_name} = {value},"
dict_file_storage["set"]["DATETIME64"] = " {col_name} = '{value}',"
dict_file_storage["set"]["TIMESTAMP"] = " {col_name} = '{value}',"
dict_file_storage["set"]["DATETIME64[NS]"] = " {col_name} = '{value}',"
dict_file_storage["set"]["TIME"] = " {col_name} = '{value}',"
dict_file_storage["set"]["NULL"] = " {col_name} = {value},"

dict_file_storage["insert"]["BOOL"] = " '{value}'"
dict_file_storage["insert"]["OBJECT"] = " '{value}'"
dict_file_storage["insert"]["INT64"] = "{value}"
dict_file_storage["insert"]["INT32"] = "{value}"
dict_file_storage["insert"]["INT16"] = "{value}"
dict_file_storage["insert"]["INT8"] = "{value}"
dict_file_storage["insert"]["CATEGORY"] = " '{value}'"
dict_file_storage["insert"]["FLOAT64"] = "{value}"
dict_file_storage["insert"]["FLOAT32"] = "{value}"
dict_file_storage["insert"]["FLOAT16"] = "{value}"
dict_file_storage["insert"]["FLOAT8"] = "{value}"
dict_file_storage["insert"]["DATETIME64"] = " '{value}'"
dict_file_storage["insert"]["TIMESTAMP"] = " '{value}'"
dict_file_storage["insert"]["DATETIME64[NS]"] = " '{value}'"
dict_file_storage["insert"]["TIME"] = " '{value}'"
dict_file_storage["insert"]["NULL"] = " {value}"

#-------------------------------------------------------------------------------------

dict_dst_vertica_short = {}

dict_dst_vertica_short["set"] = {}
dict_dst_vertica_short["insert"] = {}

dict_dst_vertica_short["set"]["VARCHAR"] = " {col_name} = '{value}',"
dict_dst_vertica_short["set"]["BINARY"] = " {col_name} = '{value}',"
dict_dst_vertica_short["set"]["VARBINARY"] = " {col_name} = '{value}',"
dict_dst_vertica_short["set"]["LONG VARBINARY"] = " {col_name} = '{value}',"
dict_dst_vertica_short["set"]["RAW"] = " {col_name} = '{value}',"
dict_dst_vertica_short["set"]["BYTE"] = " {col_name} = '{value}',"
dict_dst_vertica_short["set"]["CHAR"] = " {col_name} = '{value}',"
dict_dst_vertica_short["set"]["TEXT"] = " {col_name} = '{value}',"
dict_dst_vertica_short["set"]["TIMESTAMP"] = " {col_name} = '{value}',"
dict_dst_vertica_short["set"]["TIMESTAMPTZ[(p)]"] = " {col_name} = '{value}',"
dict_dst_vertica_short["set"]["TIMESTAMPTZ"] = " {col_name} = '{value}',"
dict_dst_vertica_short["set"]["TIMETZ"] = " {col_name} = '{value}',"
dict_dst_vertica_short["set"]["DATE"] = " {col_name} = '{value}',"
dict_dst_vertica_short["set"]["DATETIME"] =" {col_name} = '{value}',"
dict_dst_vertica_short["set"]["SMALLDATETIME"] =" {col_name} = '{value}',"
dict_dst_vertica_short["set"]["DECIMAL"] = " {col_name} = {value},"
dict_dst_vertica_short["set"]["FLOAT"] = " {col_name} = {value},"
dict_dst_vertica_short["set"]["FLOAT8"] = " {col_name} = {value},"
dict_dst_vertica_short["set"]["DOUBLE PRECISION"] = " {col_name} = {value},"
dict_dst_vertica_short["set"]["BOOLEAN"] = " {col_name} = '{value}',"
dict_dst_vertica_short["set"]["INT"] = " {col_name} = {value},"
dict_dst_vertica_short["set"]["NUMERIC"] = " {col_name} = {value},"
dict_dst_vertica_short["set"]["SMALLINT"] = " {col_name} = {value},"
dict_dst_vertica_short["set"]["TINYINT"] = " {col_name} = {value},"
dict_dst_vertica_short["set"]["INTEGER"] = " {col_name} = {value},"
dict_dst_vertica_short["set"]["BIGINT"] = " {col_name} = {value},"
dict_dst_vertica_short["set"]["INT8"] = " {col_name} = {value},"
dict_dst_vertica_short["set"]["NULL"] = " {col_name} = {value},"


dict_dst_vertica_short["insert"]["VARCHAR"] = " '{value}'"
dict_dst_vertica_short["insert"]["BINARY"] = " '{value}'"
dict_dst_vertica_short["insert"]["VARBINARY"] = " '{value}'"
dict_dst_vertica_short["insert"]["LONG VARBINARY"] = " '{value}'"
dict_dst_vertica_short["insert"]["RAW"] = " '{value}'"
dict_dst_vertica_short["insert"]["BYTE"] = " '{value}'"
dict_dst_vertica_short["insert"]["CHAR"] = " '{value}'"
dict_dst_vertica_short["insert"]["TEXT"] = " '{value}'"
dict_dst_vertica_short["insert"]["TIMESTAMP"] = " '{value}'"
dict_dst_vertica_short["insert"]["TIMESTAMPTZ[(p)]"] = " '{value}'"
dict_dst_vertica_short["insert"]["TIMESTAMPTZ"] = " '{value}'"
dict_dst_vertica_short["insert"]["TIMETZ"] = " '{value}'"
dict_dst_vertica_short["insert"]["DATE"] = " '{value}'"
dict_dst_vertica_short["insert"]["DATETIME"] = " '{value}'"
dict_dst_vertica_short["insert"]["SMALLDATETIME"] = " '{value}'"
dict_dst_vertica_short["insert"]["DECIMAL"] = "{value}"
dict_dst_vertica_short["insert"]["FLOAT"] = "{value}"
dict_dst_vertica_short["insert"]["FLOAT8"] = "{value}"
dict_dst_vertica_short["insert"]["DOUBLE PRECISION"] = "{value}"
dict_dst_vertica_short["insert"]["BOOLEAN"] = " '{value}'"
dict_dst_vertica_short["insert"]["INT"] = "{value}"
dict_dst_vertica_short["insert"]["NUMERIC"] = "{value}"
dict_dst_vertica_short["insert"]["SMALLINT"] = "{value}"
dict_dst_vertica_short["insert"]["TINYINT"] = "{value}"
dict_dst_vertica_short["insert"]["INTEGER"] = "{value}"
dict_dst_vertica_short["insert"]["BIGINT"] = "{value}"
dict_dst_vertica_short["insert"]["INT8"] = "{value}"
dict_dst_vertica_short["insert"]["NULL"] = " {value}"

#-------------------------------------------------------------------------------------


dict_mongodb = {}

dict_mongodb["set"] = {}
dict_mongodb["insert"] = {}

dict_mongodb["set"]["DICTIONARY"] = " {col_name} = '{value}',"
dict_mongodb["set"]["LIST"] = " {col_name} = '{value}',"
dict_mongodb["set"]["INTEGER"] = " {col_name} = {value},"
dict_mongodb["set"]["DECIMAL"] = " {col_name} = {value},"
dict_mongodb["set"]["BOOLEAN"] = " {col_name} = '{value}',"
dict_mongodb["set"]["STRING"] = " {col_name} = '{value}',"
dict_mongodb["set"]["DATETIME"] = " {col_name} = '{value}',"
dict_mongodb["set"]["DATE"] = " {col_name} = '{value}',"
dict_mongodb["set"]["TIME"] = " {col_name} = {value},"
dict_mongodb["set"]["NULL"] = " {col_name} = {value},"

dict_mongodb["insert"]["DICTIONARY"] =  " '{value}'"
dict_mongodb["insert"]["LIST"] =  " '{value}'"
dict_mongodb["insert"]["INTEGER"] = "{value}"
dict_mongodb["insert"]["DECIMAL"] = "{value}"
dict_mongodb["insert"]["BOOLEAN"] =  " '{value}'"
dict_mongodb["insert"]["STRING"] =  " '{value}'"
dict_mongodb["insert"]["DATETIME"] = "TMS"
dict_mongodb["insert"]["DATE"] =  " '{value}'"
dict_mongodb["insert"]["TIME"] = "{value}"
dict_mongodb["insert"]["NULL"] = " {value}"

#-------------------------------------------------------------------------------------

merge_stmt_dict = {}
merge_stmt_dict["MYSQL"] = dict_my_sql
merge_stmt_dict["SQLSERVER"] = dict_sql_server
merge_stmt_dict["POSTGRES"] = dict_postgres
merge_stmt_dict["ORACLE"] = dict_oracle
merge_stmt_dict["DB2"] = dict_db2
merge_stmt_dict["TERADATA"] = dict_tera_data
merge_stmt_dict["SAPHANA"] = dict_sap_hana
merge_stmt_dict["SNOWFLAKE"] = dict_snowflake
merge_stmt_dict['S4HANA'] = dict_rfc 
merge_stmt_dict['BW4HANA'] = dict_rfc 
merge_stmt_dict['RFC'] = dict_rfc 
merge_stmt_dict['BIGQUERY'] = dict_big_query
merge_stmt_dict['FILE'] = dict_file_storage
merge_stmt_dict['VERTICA'] = dict_dst_vertica_short
merge_stmt_dict['MONGODB'] = dict_mongodb   